---
apiVersion: v1
kind: Service
metadata:
  name: angular-carousel
spec:
  selector:
    app: angular-carousel
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: angular-carousel
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-carousel
        tier: backend
        track: stable
    spec:
      containers:
        - name: angular-carousel
          image: "samraazeem/angular-carousel:nagp"
          ports:
            - name: http
              containerPort: 80
