---
apiVersion: v1
kind: Service
metadata:
  name: angularCarousel
spec:
  selector:
    app: angularCarousel
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: angularCarousel
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: angularCarousel
        tier: backend
        track: stable
    spec:
      containers:
        - name: angularCarousel
          image: "samraazeem/angular-carousel:nagp"
          ports:
            - name: http
              containerPort: 80
