apiVersion: apps/v1
kind: Deployment
metadata:
  name: advn-microservice
  labels:
    app: nagp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp
  template:
    metadata:
      labels:
        app: nagp
    spec:
      containers:
      - name: advn-microservice-nagp
        image: samraazeem/angular-carousel:nagp
        ports:
        - containerPort: 80